zuul:
  ignoredServices: "*"  
  routes:
    persons:
        path: /persons/**
        serviceId: person-service
        stripPrefix: false
server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/
    registerWithEureka: true
